Repository cookiecutter/cookiecutter, pull requests merged in 2018-03, with the labels that each got.

#1026 pydocstyle for utils.py
  cookiecutter/utils.py
Labels: code style

#1052 added another flask starter project
  README.rst
Labels: template

#1051 Add cookiecutter-awesome to section Other
  README.rst
Labels: template

#1025 Updating tutorial1
  docs/tutorial1.rst
Labels: documentation

#1019 Use tox's TOXENV environ variable
  .travis.yml
  appveyor.yml
Labels: developers

#1056 Add cookiecutter-flask-ask to README
  README.rst
Labels: template
