Repository cookiecutter/cookiecutter, pull requests merged in 2019-12, with the labels that each got.

#1257 Fix tox dependencies versions for tests
  tox.ini
Labels: 1.7.0

#1254 Updates REAMDE.md with svg badge
  README.md
Labels: 1.7.0, needs-merge

#1249 Add missing {% endif %} to Choice Variables example
  docs/advanced/choice_variables.rst
Labels: 1.7.0, documentation, waiting-for-contributor

#1260 Version bump to 1.7.0
  cookiecutter/__init__.py
  setup.cfg
  setup.py
Labels: 1.7.0

#1234 Ran pep257 for replay.py
  cookiecutter/replay.py
Labels: 1.7.0, needs-merge, needs-review

#1262 Updated docstrings in test_unzip.py to better match pep257 (#1236)
  tests/zipfile/test_unzip.py
Labels: 1.7.0

#1259 History and authors update
  AUTHORS.md
  HISTORY.md
Labels: 1.7.0
