Repository cookiecutter/cookiecutter, pull requests merged in 2019-08, with the labels that each got.

#1168 Prevent click API v7.0 from showing choices when already shown
  AUTHORS.rst
  HISTORY.rst
  cookiecutter/prompt.py
  docs/usage.rst
  setup.py
  tests/test_read_user_choice.py
Labels: needs-review

#1207 Update README badge links
  README.rst
Labels: needs-merge

#1105 Update prompt.py to match pep257 guidelines.
  cookiecutter/prompt.py
Labels: code style, needs-merge, needs-review

#1193 update link to Jinja2 extensions Documentation
  docs/advanced/template_extensions.rst
Labels: documentation, needs-merge

#1215 Require pip 9.0.0 or newer for tox environments
  appveyor.yml
  tox.ini
Labels: high-priority

#1217 Update file mode for hooks.py to be not executable
  cookiecutter/hooks.py
Labels: bug, high-priority
