Repository cookiecutter/cookiecutter, pull requests merged in 2019-07, with the labels that each got.

#1127 Fix for DeprecationWarning (about regular expression flags) on python 3.6
  HISTORY.rst
  cookiecutter/repository.py
Labels: code-quality-cleanup, needs-merge

#1183 Authors links fix
  AUTHORS.rst
Labels: needs-merge

#1093 added cookiecutter-django-dokku to README.rst
  README.rst
Labels: needs-merge, template

#1181 Remove EOL Python Versions 3.3 and 3.4
  .travis.yml
  CONTRIBUTING.rst
  README.rst
  appveyor.yml
  docs/contributor_guidelines.rst
  docs/contributor_testing.rst
  docs/installation.rst
  setup.py
  tox.ini
Labels: needs-merge

#1189 Document use of cookiecutter-template topic on GitHub
  README.rst
Labels: needs-review

#1192 Avoids tox/pip failures on old systems
  tox.ini
Labels: needs-merge, needs-review

#1195 Generalize linter calling via pre-commit
  .pre-commit-config.yaml
  .travis.yml
  CONTRIBUTING.rst
  README.rst
  case_studies.rst
  docs/conf.py
  docs/contributing.rst
  docs/contributor_guidelines.rst
  docs/core_committer_guide.rst
  docs/sprint-contributors.rst
  docs/tutorial1.rst
  setup.cfg
  tests/fake-repo-tmpl/cookiecutter.json
  tests/fake-repo-tmpl/{{cookiecutter.repo_name}}/README.rst
  tests/test_generate_context.py
  tox.ini
Labels: needs-review

#1184 Add file:// as a suitable protocol (#1)
  cookiecutter/repository.py
  docs/usage.rst
  tests/repository/test_is_repo_url.py
Labels: needs-merge, needs-review

#1197 Fix typos
  AUTHORS.rst
  HISTORY.rst
  README.rst
  cookiecutter/zipfile.py
  docs/advanced/templates_in_context.rst
Labels: needs-merge
