Repository cookiecutter/cookiecutter, pull requests merged in 2020-04, with the labels that each got.

#1356 Configure release-drafter
  .github/labels.yml
  .github/release-drafter.yml
Labels: CI/CD

#1360 Add CI/CD steps for Github actions to speedup CI/CD
  .github/workflows/main.yml
  .travis.yml
  setup.cfg
  tests/test_cli.py
Labels: CI/CD

#1362 Updated: release-drafter configuration to match our changelog format
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: CI/CD

#1363 Removed: Appveyor CI/CD engine
  appveyor.yml
Labels: CI/CD, deprecated

#1366 Bulk changelog update for merged pull requests
  HISTORY.md
Labels: documentation, skip-changelog

#1367 Drop appveyor referrences
  CONTRIBUTING.md
  README.md
  tests/repository/test_is_repo_url.py
Labels: skip-changelog, tests

#1365 Added: GitHub Action to build Sphinx docs and store artefacts
  .github/workflows/docs.yml
  tox.ini
Labels: CI/CD, needs-review

#1377 Added: docstrings for cookiecutter test files, updated fixtures syntax
  tests/conftest.py
  tests/test_environment.py
  tests/test_exceptions.py
  tests/test_generate_copy_without_render.py
  tests/test_get_user_config.py
  tests/test_output_folder.py
Labels: code style, needs-review, tests

#1380 tests: test_prompt Exception tests refactoring
  cookiecutter/prompt.py
  tests/test_prompt.py
Labels: code style, needs-review, tests

#1371 Added docstrings to `tests/repository` directory
  tests/repository/test_determine_repo_dir_clones_repo.py
  tests/repository/test_determine_repo_dir_finds_existing_cookiecutter.py
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/repository/test_is_repo_url.py
  tests/repository/test_repository_has_cookiecutter_json.py
Labels: code style, needs-review, tests

#1372 Tests refactoring: test_generate_hooks refactored
  tests/test-shellhooks-win/hooks/post_gen_project.bat
  tests/test-shellhooks-win/hooks/pre_gen_project.bat
  tests/test-shellhooks-win/input{{cookiecutter.shellhooks}}/README.rst
  tests/test-shellhooks/hooks/post_gen_project.sh
  tests/test-shellhooks/hooks/pre_gen_project.sh
  tests/test-shellhooks/input{{cookiecutter.shellhooks}}/README.rst
  tests/test_generate_hooks.py
Labels: code style, needs-review, tests

#1373 Added: docstrings for extensions feature test files
  tests/test-extensions/custom-extension-post/hooks/post_gen_project.py
  tests/test-extensions/custom-extension-pre/hooks/pre_gen_project.py
  tests/test-extensions/hello_extension/hello_extension.py
  tests/test_custom_extensions_in_hooks.py
  tests/test_default_extensions.py
Labels: code style, needs-review, tests

#1379 Tests refactoring: test-generate_context
  tests/test_generate_context.py
Labels: code style, needs-review, tests

#1376 Added: docstrings for cookiecutter test files
  tests/test_log.py
  tests/test_repo_not_found.py
  tests/test_specify_output_dir.py
  tests/test_utils.py
  tests/vcs/test_identify_repo.py
  tests/vcs/test_is_vcs_installed.py
Labels: code style, needs-review, tests

#1375 tests: docstrings for invocation test files
  tests/test_cookiecutter_invocation.py
  tests/test_cookiecutter_local_no_input.py
  tests/test_cookiecutter_local_with_input.py
Labels: code style, needs-review, tests

#1374 tests: refactored test_abort_generate_on_hook_error
  tests/hooks-abort-render/hooks/post_gen_project.py
  tests/hooks-abort-render/hooks/pre_gen_project.py
  tests/test_abort_generate_on_hook_error.py
Labels: code style, needs-review, tests

#1369 Tests refactoring: test_abbreviation_expansion tests
  tests/repository/test_abbreviation_expansion.py
Labels: code style, needs-review, tests

#1370 Updated: get_config Function exception extended with config file path information
  cookiecutter/config.py
  tests/test_get_config.py
Labels: bug, code style, needs-review

#1378 tests: refactoring of test_generate
  tests/test_generate_file.py
  tests/test_generate_files.py
Labels: code style, needs-review, tests

#1361 Reformatted readme file and removed outdated information
  README.md
Labels: documentation, needs-review

#1381 Remove docstrings exceptions from flake8
  setup.cfg
Labels: needs-review, tests

#1368 Added: Black formatting verification for whole project
  .pre-commit-config.yaml
  cookiecutter/cli.py
  cookiecutter/config.py
  cookiecutter/environment.py
  cookiecutter/exceptions.py
  cookiecutter/extensions.py
  cookiecutter/generate.py
  cookiecutter/hooks.py
  cookiecutter/main.py
  cookiecutter/prompt.py
  cookiecutter/repository.py
  cookiecutter/utils.py
  cookiecutter/vcs.py
  cookiecutter/zipfile.py
  docs/ccext.py
  docs/conf.py
  pyproject.toml
  setup.py
  tests/conftest.py
  tests/replay/test_dump.py
  tests/replay/test_load.py
  tests/replay/test_replay.py
  tests/repository/test_abbreviation_expansion.py
  tests/repository/test_determine_repo_dir_clones_repo.py
  tests/repository/test_determine_repo_dir_finds_existing_cookiecutter.py
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/repository/test_determine_repository_should_use_local_repo.py
  tests/repository/test_is_repo_url.py
  tests/test_cli.py
  tests/test_cookiecutter_invocation.py
  tests/test_cookiecutter_local_no_input.py
  tests/test_cookiecutter_local_with_input.py
  tests/test_custom_extensions_in_hooks.py
  tests/test_default_extensions.py
  tests/test_exceptions.py
  tests/test_generate_copy_without_render.py
  tests/test_generate_file.py
  tests/test_generate_files.py
  tests/test_get_config.py
  tests/test_get_user_config.py
  tests/test_hooks.py
  tests/test_log.py
  tests/test_main.py
  tests/test_output_folder.py
  tests/test_prompt.py
  tests/test_read_user_choice.py
  tests/test_read_user_dict.py
  tests/test_read_user_yes_no.py
  tests/test_specify_output_dir.py
  tests/test_utils.py
  tests/vcs/test_clone.py
  tests/vcs/test_identify_repo.py
  tests/vcs/test_is_vcs_installed.py
  tests/zipfile/test_unzip.py
Labels: code style

#1383 Prepare release 1.7.1
  .github/release-drafter.yml
  HISTORY.md
  cookiecutter/__init__.py
  setup.py
Labels: documentation, skip-changelog

#1385 Fixed: Jinja2&Six version limits causing build errors with ansible project (#1384)
  setup.py
Labels: bug

#1387 MANIFEST: Fix file name extensions
  MANIFEST.in
Labels: bug

#1144 Fixed: Fail with gitolite repositories
  cookiecutter/vcs.py
  tests/vcs/test_clone.py
Labels: bug
