Repository cookiecutter/cookiecutter, pull requests merged in 2020-05, with the labels that each got.

#1395 Fixed: Replaced no longer maintained pipsi by pipx
  docs/installation.rst
Labels: documentation

#1390 Fixed: Comma in README.md
  README.md
Labels: documentation

#1391 Changed: README.md PyPI URLs changed to the modern PyPI last version
  README.md
Labels: documentation

#1397 Added: Example for conditional files / directories in hooks
  docs/advanced/hooks.rst
Labels: documentation

#1400 Added: Automatic PyPI deploy on tag creation
  .github/workflows/pip-publish.yml
Labels: CI/CD

#1386 Remove support for python2.7
  .github/workflows/main.yml
  .travis.yml
  CONTRIBUTING.md
  README.md
  cookiecutter/vcs.py
  cookiecutter/zipfile.py
  docs/installation.rst
  pyproject.toml
  setup.py
  tox.ini
Labels: breaking-change

#1406 Tests refactoring: test_utils write issues fixed #1405
  tests/test_utils.py
Labels: code style, enhancement, needs-review

#1404 Removed: Bumpversion, setup.py arguments.
  cookiecutter/__init__.py
  setup.cfg
  setup.py
Labels: code style, deprecated, needs-review

#1339 Render variables starting with an underscore.
  AUTHORS.md
  cookiecutter/prompt.py
  docs/advanced/index.rst
  docs/advanced/private_variables.rst
  tests/test_prompt.py
Labels: enhancement, needs tests, needs-docs

#1402 Making code python 3 only: Remove python2 u' sign, fix some strings
  cookiecutter/cli.py
  cookiecutter/config.py
  cookiecutter/hooks.py
  cookiecutter/log.py
  cookiecutter/prompt.py
  cookiecutter/utils.py
  cookiecutter/zipfile.py
  docs/conf.py
  tests/conftest.py
  tests/replay/conftest.py
  tests/test_cli.py
  tests/test_generate_context.py
  tests/test_generate_copy_without_render.py
  tests/test_generate_files.py
  tests/test_get_config.py
  tests/test_hooks.py
  tests/test_log.py
  tests/test_prompt.py
  tests/test_specify_output_dir.py
  tests/vcs/test_clone.py
Labels: code style, feature, needs-review

#1408 Python3: Changed io.open to build-in open (PEP3116)
  cookiecutter/config.py
  cookiecutter/generate.py
  cookiecutter/hooks.py
  tests/repository/test_determine_repo_dir_finds_existing_cookiecutter.py
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/test_default_extensions.py
  tests/test_generate_files.py
Labels: code style

#839 Added: Path templates will be rendered when copy_without_render used
  cookiecutter/generate.py
  docs/advanced/copy_without_render.rst
  tests/test-generate-copy-without-render/{{cookiecutter.repo_name}}/{{cookiecutter.repo_name}}-rendered/README.md
  tests/test_generate_copy_without_render.py
Labels: breaking-change, feature

#974 Changed: Generated projects can use multiple type hooks at same time. (sh + py)
  cookiecutter/hooks.py
  tests/test_hooks.py
Labels: enhancement

#992 Added: CLI option to ignore hooks
  .gitignore
  cookiecutter/cli.py
  cookiecutter/generate.py
  cookiecutter/main.py
  tests/test_cli.py
  tests/test_generate_hooks.py
  tests/test_specify_output_dir.py
  tox.ini
Labels: enhancement

#1034 Added: _output_dir to cookiecutter context
  cookiecutter/main.py
  tests/test_cli.py
Labels: enhancement

#1414 Fixed: Values encoding on Windows
  cookiecutter/generate.py
  tests/test-generate-context/non_ascii.json
  tests/test_generate_context.py
Labels: bug, windows

#906 Added: --replay-file cli option, for replay file distributing
  cookiecutter/cli.py
  cookiecutter/main.py
  cookiecutter/replay.py
  docs/advanced/replay.rst
  tests/replay/test_replay.py
  tests/test_cli.py
  tests/test_main.py
Labels: feature

#1419 Added: Jinja2 Environment extension on files generation stage
  cookiecutter/generate.py
  cookiecutter/prompt.py
  tests/test-generate-files/input{{cookiecutter.food}}/simple-with-conditions.txt
  tests/test_generate_files.py
Labels: enhancement

#1096 Added: --list-installed cli option, listing already downloaded cookiecutter packages
  cookiecutter/cli.py
  tests/test_cli.py
  tests/test_cookiecutter_invocation.py
Labels: feature
