Repository cookiecutter/cookiecutter, pull requests merged in 2020-03, with the labels that each got.

#1076 Add skip-if-file-exists when doing overwrite-if-exists
  cookiecutter/cli.py
  cookiecutter/generate.py
  cookiecutter/main.py
  tests/test_cli.py
  tests/test_generate_files.py
  tests/test_specify_output_dir.py
Labels: enhancement

#1335 Fix broken tests
  tests/test_cli.py
  tests/test_cookiecutter_invocation.py
Labels: bug

#1332 Minor gramatical fix.
  docs/advanced/hooks.rst
Labels: documentation

#1336 Add slugify template filter
  cookiecutter/environment.py
  cookiecutter/extensions.py
  docs/advanced/template_extensions.rst
  setup.py
  tests/test-extensions/default/cookiecutter.json
  tests/test_default_extensions.py
Labels: enhancement
