Repository cookiecutter/cookiecutter, pull requests merged in 2020-01, with the labels that each got.

#1225 Don't install whichcraft on Py>=3.
  cookiecutter/vcs.py
  setup.py
Labels: 1.7.1, needs-merge, needs-review

#1224 Enable multiple templates per repository
  cookiecutter/cli.py
  cookiecutter/main.py
  cookiecutter/repository.py
  docs/advanced/directories.rst
  docs/advanced/index.rst
  tests/fake-repo-dir/my-dir/cookiecutter.json
  tests/fake-repo-dir/my-dir/{{cookiecutter.repo_name}}/README.rst
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/test_cli.py
Labels: 1.7.1, enhancement, needs-merge

#1200 Add a random_ascii_string() global function.
  cookiecutter/environment.py
  cookiecutter/extensions.py
  docs/advanced/template_extensions.rst
  tests/files/{{cookiecutter.random_string_file}}.txt
  tests/test_generate_file.py
Labels: 1.8.0, enhancement, needs-merge, needs-review

#1279 ci: disable coverage comment
  codecov.yml
Labels: 1.7.1, code-quality-cleanup

#1272 Add pep257 docstring suggestions for tests/conftests.py
  tests/conftest.py
Labels: 1.7.1, needs-review

#1270 Add docstrings for "./tests/replay/conftest.py"
  tests/replay/conftest.py
Labels: 1.7.1, needs-review

#1273 Add pep257 docstring for docs/__init__.py
  docs/__init__.py
Labels: 1.7.1, needs-review

#1284 test: enable flake8-docstrings
  .pre-commit-config.yaml
  cookiecutter/extensions.py
  docs/conf.py
  setup.cfg
  tests/__init__.py
  tests/test-extensions/hello_extension/__init__.py
  tests/test-extensions/hello_extension/hello_extension.py
  tests/test_read_user_dict.py
Labels: code-quality-cleanup

#1286 D205: rule activation
  .pre-commit-config.yaml
  setup.cfg
  tests/replay/test_dump.py
  tests/replay/test_load.py
  tests/replay/test_replay.py
  tests/repository/test_determine_repo_dir_clones_repo.py
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/repository/test_determine_repository_should_use_local_repo.py
  tests/test_cookiecutter_invocation.py
  tests/test_cookiecutter_local_no_input.py
  tests/test_cookiecutter_local_with_input.py
  tests/test_find.py
  tests/test_generate_context.py
  tests/test_generate_copy_without_render.py
  tests/test_generate_file.py
  tests/test_generate_files.py
  tests/test_generate_hooks.py
  tests/test_get_config.py
  tests/test_get_user_config.py
  tests/test_hooks.py
  tests/test_log.py
  tests/test_main.py
  tests/test_output_folder.py
  tests/test_prompt.py
  tests/test_read_user_dict.py
  tests/test_read_user_variable.py
  tests/test_read_user_yes_no.py
  tests/test_utils.py
  tests/vcs/test_clone.py
Labels: code-quality-cleanup

#941 Use a more lightweight python porting library.
  cookiecutter/prompt.py
  cookiecutter/replay.py
  setup.py
  tests/test_prompt.py
Labels: enhancement, high-priority

#1283 D100: Add missing docstring headers
  cookiecutter/zipfile.py
  docs/ccext.py
  docs/conf.py
  setup.cfg
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/hooks-abort-render/hooks/post_gen_project.py
  tests/hooks-abort-render/hooks/pre_gen_project.py
  tests/replay/conftest.py
  tests/repository/test_abbreviation_expansion.py
  tests/repository/test_determine_repo_dir_clones_repo.py
  tests/repository/test_determine_repo_dir_finds_existing_cookiecutter.py
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/repository/test_determine_repository_should_use_local_repo.py
  tests/repository/test_is_repo_url.py
  tests/repository/test_repository_has_cookiecutter_json.py
  tests/test-extensions/custom-extension-post/hooks/post_gen_project.py
  tests/test-extensions/custom-extension-pre/hooks/pre_gen_project.py
  tests/test-extensions/hello_extension/hello_extension.py
  tests/test-output-folder/{{cookiecutter.test_name}}/{{cookiecutter.folder_name}}/{{cookiecutter.filename}}.py
  tests/test-pyhooks/hooks/post_gen_project.py
  tests/test-pyhooks/hooks/pre_gen_project.py
  tests/test-pyshellhooks/hooks/post_gen_project.py
  tests/test-pyshellhooks/hooks/pre_gen_project.py
  tests/test_abort_generate_on_hook_error.py
  tests/test_cli.py
  tests/test_cookiecutter_invocation.py
  tests/test_cookiecutter_local_with_input.py
  tests/test_custom_extensions_in_hooks.py
  tests/test_default_extensions.py
  tests/test_environment.py
  tests/test_exceptions.py
  tests/test_find.py
  tests/test_generate_context.py
  tests/test_generate_file.py
  tests/test_generate_files.py
  tests/test_generate_hooks.py
  tests/test_get_config.py
  tests/test_hooks.py
  tests/test_log.py
  tests/test_main.py
  tests/test_output_folder.py
  tests/test_preferred_encoding.py
  tests/test_prompt.py
  tests/test_read_repo_password.py
  tests/test_read_user_choice.py
  tests/test_repo_not_found.py
  tests/test_specify_output_dir.py
  tests/test_utils.py
  tests/undefined-variable/dir-name/{{cookiecutter.project_slug}}/{{cookiecutter.foobar}}/helloworld.py
  tests/vcs/test_clone.py
  tests/vcs/test_identify_repo.py
  tests/vcs/test_is_vcs_installed.py
Labels: documentation, waiting-for-contributor
