Repository cookiecutter/cookiecutter, pull requests merged in 2021-06, with the labels that each got.

#1568 Make release-drafter diff only between master releases
  .github/release-drafter.yml
Labels: CI/CD

#1577 Adopt setuptools-scm packaging
  .github/workflows/main.yml
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement

#1569 Add support for click 8.x
  cookiecutter/prompt.py
  setup.cfg
  tests/test_read_user_dict.py
Labels: bug

#1542 enable branch coverage
  cookiecutter/vcs.py
  tests/test_utils.py
  tests/vcs/test_clone.py
  tests/zipfile/test_unzip.py
  tox.ini
Labels: tests
