Repository cookiecutter/cookiecutter, pull requests merged in 2021-04, with the labels that each got.

#1521 Run coverage with matrix
  .github/workflows/coverage.yml
  .github/workflows/main.yml
  .gitignore
  .travis.yml
  AUTHORS.md
  CONTRIBUTING.md
  Makefile
  README.md
  tox.ini
Labels: CI/CD, high-priority

#1532 update AUTHOR lead
  AUTHORS.md
  README.md
Labels: enhancement

#1535 Add missing contributors
  AUTHORS.md
Labels: documentation

#1489 Replace poyo with pyyaml.
  cookiecutter/config.py
  setup.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_get_config.py
Labels: enhancement

#1496 Alert user if choice is invalid
  cookiecutter/generate.py
  tests/test_generate_context.py
Labels: enhancement

#1493 Added uuid extension to be able to generate uuids
  cookiecutter/environment.py
  cookiecutter/extensions.py
  docs/advanced/template_extensions.rst
  tests/test-extensions/default/{{cookiecutter.project_slug}}/id
  tests/test_default_extensions.py
  tests/test_environment.py
Labels: feature

#1516 config: set default on missing default_context key
  cookiecutter/config.py
  tests/test-config/valid-config.yaml
  tests/test_get_config.py
  tests/test_get_user_config.py
Labels: bug

#1468 User's JSON parse error causes ugly Python exception #809
  cookiecutter/cli.py
  tests/fake-repo-bad-json/cookiecutter.json
  tests/fake-repo-bad-json/{{cookiecutter.repo_name}}/README.rst
  tests/test_cli.py
Labels: bug, discussion
