Repository cookiecutter/cookiecutter, pull requests merged in 2021-05, with the labels that each got.

#1544 Fix author name
  LICENSE
  setup.py
Labels: documentation

#1537 Fix pull requests checklist reference
  CONTRIBUTING.md
Labels: documentation, waiting-for-contributor

#1548 allow jinja 3.0.0
  setup.py
Labels: bug

#1505 Log the error message when git clone fails, not just the return code
  cookiecutter/vcs.py
Labels: enhancement

#1504 fixes prompting private rendered dicts
  cookiecutter/prompt.py
Labels: bug

#1549 Remove direct dependency on markupsafe
  setup.py
Labels: bug

#1551 Activate workflows on stable branches
  .github/workflows/main.yml
Labels: CI/CD

#1550 Fix dependency conflicts
  .github/workflows/main.yml
  setup.py
Labels: backport, bug

#1552 Release 1.7.3
  HISTORY.md
  cookiecutter/__init__.py
  setup.py
Labels: high-priority, skip-changelog

#1553 Backport pip-publish workflow
  .github/workflows/pip-publish.yml
Labels: backport, skip-changelog

#1559 pre-commit: add bandit hook
  .bandit
  .pre-commit-config.yaml
  cookiecutter/hooks.py
  cookiecutter/vcs.py
Labels: CI/CD

#1560 add safety ci step
  .github/workflows/main.yml
  tox.ini
Labels: CI/CD

#1564 ensure filesystem isolation during tests execution
  tests/conftest.py
  tests/test_cli.py
  tests/test_get_config.py
Labels: tests
