Repository cookiecutter/cookiecutter, pull requests merged in 2022-05, with the labels that each got.

#1679 housekeeping: run pyupgrade to find remaining py27 artifacts
  cookiecutter/cli.py
  cookiecutter/config.py
  cookiecutter/environment.py
  cookiecutter/exceptions.py
  cookiecutter/extensions.py
  cookiecutter/generate.py
  cookiecutter/hooks.py
  cookiecutter/prompt.py
  cookiecutter/replay.py
  cookiecutter/utils.py
  cookiecutter/vcs.py
  cookiecutter/zipfile.py
  tests/replay/test_dump.py
  tests/replay/test_load.py
  tests/test-extensions/hello_extension/hello_extension.py
  tests/test-extensions/local_extension/local_extensions/main.py
  tests/test_default_extensions.py
  tests/test_generate_file.py
  tests/test_generate_files.py
  tests/test_hooks.py
  tests/test_prompt.py
  tests/test_read_user_choice.py
  tests/vcs/test_clone.py
Labels: code style, skip-changelog

#1682 Follow PyPA guide to release package using GitHub Actions.
  .github/workflows/pip-publish.yml
Labels: CI/CD

#1684 bump version and edit history
  HISTORY.md
  cookiecutter/__init__.py
  setup.py
Labels: CI/CD, skip-changelog

#1686 [Docs] Fix local extensions documentation
  docs/advanced/local_extensions.rst
Labels: documentation
