Repository cookiecutter/cookiecutter, pull requests merged in 2022-06, with the labels that each got.

#1689 Sanitize Mercurial branch information before checkout.
  HISTORY.md
  cookiecutter/vcs.py
  tests/vcs/test_clone.py
Labels: bug, high-priority

#1604 Fix @audreyr to @audreyfeldroy github account rename
  AUTHORS.md
  HISTORY.md
  docs/advanced/calling_from_python.rst
  docs/advanced/user_config.rst
  docs/overview.rst
  docs/tutorials/index.rst
  docs/tutorials/tutorial1.rst
  docs/usage.rst
  tests/repository/test_is_repo_url.py
  tests/vcs/test_identify_repo.py
Labels: documentation

#1592 Documentation extension: Create a Cookiecutter From Scratch tutorial
  docs/tutorials/tutorial2.rst
Labels: documentation

#1669 Add CLI option to keep project files on failure.
  cookiecutter/cli.py
  cookiecutter/generate.py
  cookiecutter/main.py
  tests/test_cli.py
  tests/test_generate_files.py
  tests/test_specify_output_dir.py
Labels: enhancement

#1691 Fixed broken links to jinja docs
  docs/advanced/dict_variables.rst
  docs/advanced/template_extensions.rst
  docs/troubleshooting.rst
Labels: documentation

#1587 Expand cli documentation relating to the no-input flag (#1543)
  cookiecutter/cli.py
  cookiecutter/main.py
  cookiecutter/prompt.py
  cookiecutter/repository.py
  cookiecutter/vcs.py
  cookiecutter/zipfile.py
  docs/advanced/suppressing_prompts.rst
Labels: documentation, code style

#1485 Added: Templates inheritance
  cookiecutter/generate.py
  docs/advanced/index.rst
  docs/advanced/templates.rst
  tests/test-templates/extends/cookiecutter.json
  tests/test-templates/extends/templates/base-requirements.jinja
  tests/test-templates/extends/templates/click-requirements.jinja
  tests/test-templates/extends/templates/pytest-requirements.jinja
  tests/test-templates/extends/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/include/cookiecutter.json
  tests/test-templates/include/templates/click-requirements.jinja
  tests/test-templates/include/templates/pytest-requirements.jinja
  tests/test-templates/include/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/no-templates/cookiecutter.json
  tests/test-templates/no-templates/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/super/cookiecutter.json
  tests/test-templates/super/templates/base-requirements.jinja
  tests/test-templates/super/templates/click-requirements.jinja
  tests/test-templates/super/templates/pytest-requirements.jinja
  tests/test-templates/super/{{cookiecutter.project_slug}}/requirements.txt
  tests/test_templates.py
Labels: feature

#1626 Added: Boolean variable support in JSON
  cookiecutter/prompt.py
  docs/advanced/boolean_variables.rst
  docs/advanced/index.rst
  tests/test_prompt.py
Labels: feature

#1704 Updated: Release drafter configuration
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: CI/CD

#1707 Added: Readthedocs build config
  .readthedocs.yaml
Labels: CI/CD

#1706 CI/CD: Tox -> Nox: Added nox configuration
  MANIFEST.in
  docs/advanced/suppressing_prompts.rst
  docs/requirements.txt
  noxfile.py
  test_requirements.txt
Labels: documentation, CI/CD

#1709 Fixed: recommonmark replaced with myst, as recommonmark is deprecated
  CONTRIBUTING.md
  docs/conf.py
  docs/requirements.txt
Labels: documentation, CI/CD

#1711 Fixed: Removed mention of packages versions, to exclude dependabot warnings alerts
  tests/test-templates/extends/templates/base-requirements.jinja
  tests/test-templates/extends/templates/click-requirements.jinja
  tests/test-templates/extends/templates/pytest-requirements.jinja
  tests/test-templates/include/templates/click-requirements.jinja
  tests/test-templates/include/templates/pytest-requirements.jinja
  tests/test-templates/include/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/no-templates/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/super/templates/base-requirements.jinja
  tests/test-templates/super/templates/click-requirements.jinja
  tests/test-templates/super/templates/pytest-requirements.jinja
  tests/test_templates.py
Labels: bug

#1712 CI/CD: Updated .pre-commit-config.yaml to use latest hooks versions
  .pre-commit-config.yaml
  setup.py
  tests/hooks-abort-render/hooks/post_gen_project.py
  tests/hooks-abort-render/hooks/pre_gen_project.py
  tests/test-pyhooks/hooks/post_gen_project.py
  tests/test-pyhooks/hooks/pre_gen_project.py
  tests/test-pyshellhooks/hooks/post_gen_project.py
  tests/test-pyshellhooks/hooks/pre_gen_project.py
Labels: CI/CD

#1713 Makefile update: Removed watchmedo and sed dependency, tox replaced with nox
  .github/workflows/docs.yml
  .gitignore
  Makefile
  docs/Makefile
  docs/_templates/package.rst_t
  docs/conf.py
  docs/cookiecutter.rst
  docs/make.bat
  docs/requirements.txt
  noxfile.py
Labels: CI/CD

#1714 CI/CD: Github actions definition minimized + Sync nox and github actions python versions
  .github/workflows/docs.yml
  .github/workflows/drafter.yml
  .github/workflows/main.yml
  .github/workflows/pip-publish.yml
  .github/workflows/tests.yml
  docs/requirements.txt
Labels: CI/CD

#1715 Fixed: Python code block in the replay documentation
  docs/advanced/replay.rst
Labels: documentation

#1717 Code quality: tests files: Simplify statements fixes
  tests/test_custom_extensions_in_hooks.py
  tests/test_default_extensions.py
  tests/test_utils.py
Labels: code style

#1716 Code quality: core files: Format replaced with f-strings
  cookiecutter/cli.py
  cookiecutter/generate.py
  cookiecutter/prompt.py
  cookiecutter/utils.py
  cookiecutter/zipfile.py
Labels: needs-review, code style

#1719 Code quality: Core files: Added exception reason reraise when exception class changed (PEP 3134)
  cookiecutter/environment.py
  cookiecutter/generate.py
  cookiecutter/hooks.py
  cookiecutter/prompt.py
  cookiecutter/vcs.py
Labels: needs-review, code style, patch

#1718 Code quality: Tests upgrade: Use pathlib for files read/write
  tests/repository/test_determine_repo_dir_finds_existing_cookiecutter.py
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/test_cli.py
  tests/test_cookiecutter_local_no_input.py
  tests/test_custom_extensions_in_hooks.py
  tests/test_default_extensions.py
  tests/test_generate_copy_without_render.py
  tests/test_generate_copy_without_render_override.py
  tests/test_generate_file.py
  tests/test_generate_files.py
  tests/test_generate_hooks.py
  tests/test_hooks.py
  tests/test_output_folder.py
  tests/test_templates.py
  tests/test_utils.py
  tests/zipfile/test_unzip.py
Labels: needs-review, code style, feature

#1721 Code quality: find.py refactored and type annotated
  cookiecutter/find.py
  docs/conf.py
  docs/requirements.txt
  tests/test_find.py
Labels: windows, needs-review, code style, CI/CD

#1722 Code quality: utils.make_sure_path_exists refactored and type annotated
  cookiecutter/generate.py
  cookiecutter/replay.py
  cookiecutter/utils.py
  cookiecutter/vcs.py
  cookiecutter/zipfile.py
  tests/replay/test_dump.py
  tests/test_utils.py
  tests/vcs/test_clone.py
Labels: code style

#1741 Easy PR! Fix typos and add minor doc updates
  cookiecutter/exceptions.py
  cookiecutter/prompt.py
  cookiecutter/repository.py
  docs/tutorials/tutorial2.rst
  setup.cfg
  tests/conftest.py
  tests/test_cli.py
Labels: documentation
