Repository cookiecutter/cookiecutter, pull requests merged in 2023-06, with the labels that each got.

#1852 Rename `master` to `main` so CI runs correctly on merge
  .github/workflows/tests.yml
Labels: CI/CD

#1795 Remove unused import from post-generate hook script example
  docs/advanced/hooks.rst
Labels: patch

#1798 fixing badge display problem
  README.md
Labels: documentation

#1760 cleanup files if panics during hooks - bugfix
  cookiecutter/generate.py
Labels: bug

#1770 Support nested config files
  cookiecutter/main.py
  docs/advanced/index.rst
  docs/advanced/nested_config_files.rst
  tests/fake-nested-templates/cookiecutter.json
  tests/fake-nested-templates/fake-project/cookiecutter.json
  tests/test_cookiecutter_nested_templates.py
Labels: enhancement, feature

#1858 Update base docs, remove tox
  CONTRIBUTING.md
  Makefile
  README.md
  noxfile.py
  setup.py
  tox.ini
Labels: documentation, CI/CD

#1864 Pretty-format JSON files
  .pre-commit-config.yaml
  tests/fake-nested-templates/cookiecutter.json
  tests/fake-nested-templates/fake-project/cookiecutter.json
  tests/fake-repo-dict/cookiecutter.json
  tests/fake-repo-dir/my-dir/cookiecutter.json
  tests/fake-repo-pre/cookiecutter.json
  tests/fake-repo-pre2/cookiecutter.json
  tests/fake-repo-tmpl/cookiecutter.json
  tests/test-extensions/custom-extension-post/cookiecutter.json
  tests/test-extensions/custom-extension-pre/cookiecutter.json
  tests/test-extensions/default/cookiecutter.json
  tests/test-extensions/local_extension/cookiecutter.json
  tests/test-extensions/unknown/cookiecutter.json
  tests/test-generate-context/choices_template.json
  tests/test-generate-context/nested_dict.json
  tests/test-generate-context/non_ascii.json
  tests/test-generate-context/test.json
  tests/test-generate-files-line-end/cookiecutter.json
  tests/test-output-folder/cookiecutter.json
  tests/test-replay/cookiedozer_load.json
  tests/test-replay/invalid_replay.json
  tests/test-templates/extends/cookiecutter.json
  tests/test-templates/include/cookiecutter.json
  tests/test-templates/no-templates/cookiecutter.json
  tests/test-templates/super/cookiecutter.json
  tests/undefined-variable/file-name/cookiecutter.json
Labels: code style, CI/CD

#1866 Use tox
  .github/release-drafter.yml
  .github/workflows/tests.yml
  CONTRIBUTING.md
  MANIFEST.in
  Makefile
  noxfile.py
  tox.ini
Labels: CI/CD

#1876 Standardize EOF newlines
  .github/ISSUE_TEMPLATE.md
  .pre-commit-config.yaml
  docs/advanced/boolean_variables.rst
  docs/advanced/local_extensions.rst
  docs/requirements.txt
  docs/usage.rst
  tests/fake-repo-bad/no-project-in-here.txt
  tests/files/syntax_error.txt
  tests/files/unicode.txt
  tests/files/{% if cookiecutter.generate_file == 'y' %}cheese.txt{% endif %}
  tests/files/{{cookiecutter.generate_file}}.txt
  tests/test-extensions/default/{{cookiecutter.project_slug}}/id
  tests/test-generate-files-nontemplated/input/simple.txt
  tests/test-generate-files-permissions/input{{cookiecutter.permissions}}/simple.txt
  tests/test-generate-files/input{{cookiecutter.food}}/simple.txt
  tests/test-output-folder/{{cookiecutter.test_name}}/folder/in_folder.txt
  tests/test-output-folder/{{cookiecutter.test_name}}/something.txt
  tests/test-templates/extends/templates/base-requirements.jinja
  tests/test-templates/extends/templates/click-requirements.jinja
  tests/test-templates/extends/templates/pytest-requirements.jinja
  tests/test-templates/extends/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/include/templates/click-requirements.jinja
  tests/test-templates/include/templates/pytest-requirements.jinja
  tests/test-templates/include/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/no-templates/{{cookiecutter.project_slug}}/requirements.txt
  tests/test-templates/super/templates/base-requirements.jinja
  tests/test-templates/super/templates/click-requirements.jinja
  tests/test-templates/super/templates/pytest-requirements.jinja
  tests/test-templates/super/{{cookiecutter.project_slug}}/requirements.txt
  tests/test_default_extensions.py
  tests/test_generate_files.py
  tests/test_output_folder.py
  tests/test_templates.py
Labels: code style
