Repository cookiecutter/cookiecutter, pull requests merged in 2023-07, with the labels that each got.

#1874 preserves original options in `_cookiecutter`
  cookiecutter/main.py
  tests/fake-repo-tmpl-_cookiecutter/cookiecutter.json
  tests/fake-repo-tmpl-_cookiecutter/{{cookiecutter.repo_name}}/README.rst
  tests/test_cli.py
  tests/test_main.py
Labels: enhancement

#1872 Add jinja env docs
  docs/advanced/index.rst
  docs/advanced/jinja_env.rst
Labels: documentation

#1879 Update `.gitignore` and cite where it was copied from
  .gitignore
Labels: CI/CD

#1881 Added support for providing human-readable prompts to the different variables
  README.md
  cookiecutter/prompt.py
  docs/advanced/human_readable_prompts.rst
  docs/advanced/index.rst
  docs/cookiecutter.rst
  tests/test_cookiecutter_local_with_input.py
  tests/test_prompt.py
Labels: enhancement

#1884 Prepare release 2.2.0
  HISTORY.md
  setup.py
Labels: documentation, CI/CD, skip-changelog

#1889 Improve gitignore
  .gitignore
Labels: CI/CD

#1890 docs: add warning for jinja2_time
  docs/advanced/template_extensions.rst
Labels: documentation

#1891 Prepare release of version 2.2.2
  HISTORY.md
  setup.py
Labels: documentation, CI/CD, skip-changelog

#1894 Back to development
  HISTORY.md
  setup.py
Labels: documentation, CI/CD, skip-changelog

#1895 Fix issue where the prompts dict was not passed for yes_no questions
  cookiecutter/prompt.py
  tests/test_prompt.py
Labels: bug

#1896 Set cookiecutter/VERSION.txt as source of truth for version number
  MANIFEST.in
  cookiecutter/VERSION.txt
  cookiecutter/__init__.py
  setup.py
Labels: bug, CI/CD

#1758 Prompt with replay file
  cookiecutter/main.py
  tests/replay/test_replay.py
  tests/test_cli.py
  tests/test_main.py
Labels: enhancement

#1904 Fix replay
  .gitignore
  cookiecutter/main.py
  tests/fake-repo-replay/cookiecutter.json
  tests/fake-repo-replay/{{cookiecutter.repo_name}}/README.md
  tests/test-replay/valid_replay.json
  tests/test_cli.py
  tests/test_main.py
Labels: bug

#1903 Support multichoice overwrite
  cookiecutter/generate.py
  tests/test_generate_context.py
Labels: bug
