Repository cookiecutter/cookiecutter, pull requests merged in 2023-11, with the labels that each got.

#1965 Update cookiecutter-plone-starter link in readme
  README.md
Labels: documentation

#1967 Update README.md
  README.md
Labels: documentation

#1961 Fix recursive context overwrites
  cookiecutter/generate.py
  tests/test_generate_context.py
Labels: bug

#1964 Add argument run to pipx command in README.md
  README.md
Labels: documentation

#1968 Fix FileExistsError when using a relative template path
  cookiecutter/utils.py
Labels: bug

#1971 Fix tutorial2 generated HTML
  docs/tutorials/tutorial2.rst
Labels: documentation

#1952 Update README.md to fix broken link
  README.md
Labels: documentation

#1949 Update README.md to include installation instructions
  README.md
Labels: documentation

#1924 Default values can be passed as a dict
  cookiecutter/config.py
  tests/test_get_user_config.py
Labels: enhancement

#1981 Implement new style for nested templates config
  cookiecutter/main.py
  cookiecutter/prompt.py
  docs/advanced/nested_config_files.rst
  tests/fake-nested-templates-old-style/cookiecutter.json
  tests/fake-nested-templates-old-style/fake-package/cookiecutter.json
  tests/fake-nested-templates/cookiecutter.json
  tests/fake-nested-templates/fake-package/cookiecutter.json
  tests/test_cookiecutter_nested_templates.py
  tests/test_prompt.py
Labels: documentation, feature

#1982 Prepare release 2.5.0
  HISTORY.md
  cookiecutter/VERSION.txt
Labels: documentation, skip-changelog

#1988 Add isort as a pre-commit hook
  .pre-commit-config.yaml
  __main__.py
  cookiecutter/__main__.py
  cookiecutter/cli.py
  cookiecutter/extensions.py
  cookiecutter/generate.py
  cookiecutter/main.py
  cookiecutter/prompt.py
  pyproject.toml
  setup.py
  tests/conftest.py
  tests/repository/test_determine_repository_should_use_local_repo.py
  tests/test-extensions/local_extension/local_extensions/main.py
  tests/test-pyhooks/hooks/pre_prompt.py
  tests/test_cli.py
  tests/test_cookiecutter_nested_templates.py
  tests/test_generate_copy_without_render.py
  tests/test_generate_copy_without_render_override.py
  tests/test_hooks.py
  tests/test_output_folder.py
  tests/test_prompt.py
  tests/test_read_user_dict.py
  tests/test_read_user_variable.py
  tests/test_read_user_yes_no.py
  tests/test_time_extension.py
Labels: code style

#1989 Support Python 3.12
  .github/workflows/pip-publish.yml
  .github/workflows/tests.yml
  README.md
  setup.py
  test_requirements.txt
  tox.ini
Labels: enhancement, documentation, CI/CD
