Repository cookiecutter/cookiecutter, pull requests merged in 2023-09, with the labels that each got.

#1932 Add missing "parent dir" symbol in tutorial 2
  docs/tutorials/tutorial2.rst
Labels: documentation

#1917 docs: add install instruction for Void Linux
  docs/installation.rst
Labels: documentation

#1912 Remove colons from exemplary prompt messages
  docs/advanced/human_readable_prompts.rst
Labels: documentation

#1934 Update the black pre-commit hook URL and version
  .pre-commit-config.yaml
Labels: CI/CD

#1940 Fix prompt counter.
  cookiecutter/prompt.py
Labels: bug

#1920 Fix variables with null default not being required (#1919)
  cookiecutter/prompt.py
  tests/test_read_user_variable.py
Labels: bug

#1937 Use UTF-8 for file reading/writing
  cookiecutter/__init__.py
  cookiecutter/replay.py
Labels: CI/CD

#1923 add checkout details to the context (fixes #1759)
  cookiecutter/main.py
  tests/test_cli.py
Labels: enhancement

#1922 Fix nested templates in Git repository
  cookiecutter/main.py
Labels: bug

#1941 Prepare release 2.3.1
  HISTORY.md
  cookiecutter/VERSION.txt
Labels: documentation, skip-changelog

#1942 Gracefully handle files with mixed lined endings
  cookiecutter/generate.py
  tests/test_generate_file.py
Labels: enhancement

#1947 update main docstrings to include overwrite_if_exists and skip_if_file_exists
  cookiecutter/main.py
Labels: documentation

#1951 Prepare release 2.4.0
  .github/release-drafter.yml
  HISTORY.md
  README.md
  cookiecutter/VERSION.txt
Labels: documentation, CI/CD, skip-changelog
