Repository cookiecutter/cookiecutter, pull requests merged in 2024-03, with the labels that each got.

#2012 Use 'Ruff' for linting and formatting
  .pre-commit-config.yaml
  MANIFEST.in
  cookiecutter/cli.py
  cookiecutter/hooks.py
  cookiecutter/main.py
  cookiecutter/prompt.py
  cookiecutter/vcs.py
  cookiecutter/zipfile.py
  docs/conf.py
  pyproject.toml
  setup.cfg
  tests/repository/test_determine_repo_dir_clones_repo.py
  tests/repository/test_determine_repo_dir_finds_subdirectories.py
  tests/repository/test_determine_repository_should_use_local_repo.py
  tests/test-extensions/local_extension/local_extensions/__init__.py
  tests/test_cli.py
  tests/test_cookiecutter_invocation.py
  tests/test_generate_files.py
  tests/test_get_user_config.py
  tests/test_log.py
  tests/test_prompt.py
  tests/test_read_user_dict.py
  tests/test_time_extension.py
Labels: code style

#2014 Add 'pyflakes' lints
  pyproject.toml
  tests/test-extensions/local_extension/local_extensions/__init__.py
Labels: code style

#2016 Add 'pygrep' lints
  docs/conf.py
  pyproject.toml
Labels: code style

#2020 enable lint groups for string formatting
  cookiecutter/extensions.py
  cookiecutter/prompt.py
  pyproject.toml
Labels: code style

#2036 README: Update outdated shield branch names
  README.md
Labels: documentation

#2040 move configuration from setup.cfg to pyproject.toml
  pyproject.toml
  setup.cfg
Labels: CI/CD

#2042 shrink mypy whitelist for cookiecutter.hooks
  cookiecutter/hooks.py
  pyproject.toml
Labels: code style, CI/CD

#2041 shrink mypy whitelist for cookiecutter.generate
  cookiecutter/find.py
  cookiecutter/generate.py
  pyproject.toml
Labels: code style, CI/CD

#1991 [1518] Directory Name Render and Create Fix
  cookiecutter/cli.py
  cookiecutter/exceptions.py
  cookiecutter/generate.py
  tests/test_generate_files.py
Labels: bug

#2029 Convert CLI provided strings to booleans for boolean config variables
  cookiecutter/generate.py
  tests/test_generate_context.py
Labels: bug
