Repository cookiecutter/cookiecutter, pull requests merged in 2024-02, with the labels that each got.

#1997 fix: modifying start and end variable strings
  cookiecutter/find.py
  cookiecutter/generate.py
  cookiecutter/hooks.py
  cookiecutter/prompt.py
  cookiecutter/utils.py
  cookiecutter/vcs.py
  cookiecutter/zipfile.py
  tests/fake-repo-pre2/{%{cookiecutter.repo_name}%}/README.rst
  tests/test_cookiecutter_local_no_input.py
  tests/test_find.py
  tests/test_generate_files.py
  tests/test_prompt.py
  tests/test_utils.py
Labels: enhancement

#2010 Fix regression #2009: Adding value to nested dicts broken
  cookiecutter/generate.py
  tests/test-generate-context/nested_dict_additional.json
  tests/test_generate_context.py
Labels: bug, regression

#2022 Prepare release 2.6.0
  HISTORY.md
  cookiecutter/VERSION.txt
Labels: documentation, skip-changelog
